In [1]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,MaxPool2D,Flatten,Conv2D,Dropout

In [2]:
(X_train,Y_train),(X_test,y_test)=mnist.load_data();    # importing the dataset from keras

In [3]:
X_test=X_test.reshape((X_test.shape[0],X_test.shape[1],X_test.shape[2],1))    

In [4]:
X_train=X_train.reshape((X_train.shape[0]),X_train.shape[1],X_train.shape[2],1)

In [5]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [6]:
#Normalizing the pixel values
X_train=X_train/255
X_test=X_test/255
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [7]:
print(Y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [8]:
model=Sequential()


In [9]:
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))              #specifying 32 fillers of size (3*3)
                                                                                 #input size=28 by 28 and are greyscale(1)

In [10]:
model.add(MaxPool2D(2,2))

In [11]:
# Adding fully connected Layer
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [12]:
#Output layer
model.add(Dense(10,activation='softmax'))


In [13]:
#compilation
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [14]:
model.fit(X_train,Y_train,epochs=20)

Epoch 1/20
1875/1875 [==============================] - 19s 10ms/step - loss: 0.1571 - accuracy: 0.9541
Epoch 2/20
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0522 - accuracy: 0.9845
Epoch 3/20
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0343 - accuracy: 0.9891
Epoch 4/20
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0223 - accuracy: 0.9930
Epoch 5/20
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0158 - accuracy: 0.9947
Epoch 6/20
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0111 - accuracy: 0.9965
Epoch 7/20
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0105 - accuracy: 0.9966
Epoch 8/20
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0068 - accuracy: 0.9977
Epoch 9/20
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0055 - accuracy: 0.9981
Epoch 10/20
1875/1875 [==============================] - 19s 10m

In [16]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 2s 5ms/step - loss: 0.0800 - accuracy: 0.9857


[0.07999783009290695, 0.9857000112533569]